
package pl.edu.pwr.services.ner_old;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "nerws", targetNamespace = "http://156.17.134.42/nerws/", wsdlLocation = "http://156.17.134.42/nerws/nerws.wsdl")
public class Nerws_Service
    extends Service
{

    private final static URL NERWS_WSDL_LOCATION;
    private final static WebServiceException NERWS_EXCEPTION;
    private final static QName NERWS_QNAME = new QName("http://156.17.134.42/nerws/", "nerws");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://156.17.134.42/nerws/nerws.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NERWS_WSDL_LOCATION = url;
        NERWS_EXCEPTION = e;
    }

    public Nerws_Service() {
        super(__getWsdlLocation(), NERWS_QNAME);
    }

    public Nerws_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), NERWS_QNAME, features);
    }

    public Nerws_Service(URL wsdlLocation) {
        super(wsdlLocation, NERWS_QNAME);
    }

    public Nerws_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NERWS_QNAME, features);
    }

    public Nerws_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Nerws_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Nerws
     */
    @WebEndpoint(name = "nerwsSOAP")
    public Nerws getNerwsSOAP() {
        return super.getPort(new QName("http://156.17.134.42/nerws/", "nerwsSOAP"), Nerws.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Nerws
     */
    @WebEndpoint(name = "nerwsSOAP")
    public Nerws getNerwsSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://156.17.134.42/nerws/", "nerwsSOAP"), Nerws.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NERWS_EXCEPTION!= null) {
            throw NERWS_EXCEPTION;
        }
        return NERWS_WSDL_LOCATION;
    }

}
