
package pl.edu.pwr.services.tagger;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TaggerServicePortType", targetNamespace = "http://ws.clarin-pl.eu/wsg/tagger/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TaggerServicePortType {


    /**
     * Send request to server
     * 
     * @param parameters
     * @return
     *     returns pl.edu.pwr.services.tagger.SendRequestResponseType
     */
    @WebMethod(operationName = "SendRequest", action = "http://ws.clarin-pl.eu/wsg/tagger/#SendRequest")
    @WebResult(name = "SendRequestResponse", targetNamespace = "http://ws.clarin-pl.eu/wsg/tagger/", partName = "parameters")
    public SendRequestResponseType sendRequest(
        @WebParam(name = "SendRequest", targetNamespace = "http://ws.clarin-pl.eu/wsg/tagger/", partName = "parameters")
        SendRequestRequestType parameters);

    /**
     * Ask server for status of request with specific token
     * 
     * @param parameters
     * @return
     *     returns pl.edu.pwr.services.tagger.CheckStatusResponseType
     */
    @WebMethod(operationName = "CheckStatus", action = "http://ws.clarin-pl.eu/wsg/tagger/#CheckStatus")
    @WebResult(name = "CheckStatusResponse", targetNamespace = "http://ws.clarin-pl.eu/wsg/tagger/", partName = "parameters")
    public CheckStatusResponseType checkStatus(
        @WebParam(name = "CheckStatus", targetNamespace = "http://ws.clarin-pl.eu/wsg/tagger/", partName = "parameters")
        CheckStatusRequestType parameters);

    /**
     * Get result from server
     * 
     * @param parameters
     * @return
     *     returns pl.edu.pwr.services.tagger.GetResultResponseType
     */
    @WebMethod(operationName = "GetResult", action = "http://ws.clarin-pl.eu/wsg/tagger/#GetResult")
    @WebResult(name = "GetResultResponse", targetNamespace = "http://ws.clarin-pl.eu/wsg/tagger/", partName = "parameters")
    public GetResultResponseType getResult(
        @WebParam(name = "GetResult", targetNamespace = "http://ws.clarin-pl.eu/wsg/tagger/", partName = "parameters")
        GetResultRequestType parameters);

    /**
     * Get result from server in JSON
     * 
     * @param parameters
     * @return
     *     returns pl.edu.pwr.services.tagger.GetResultJSONResponseType
     */
    @WebMethod(operationName = "GetResultJSON", action = "http://ws.clarin-pl.eu/wsg/tagger/#GetResultJSON")
    @WebResult(name = "GetResultJSONResponse", targetNamespace = "http://ws.clarin-pl.eu/wsg/tagger/", partName = "parameters")
    public GetResultJSONResponseType getResultJSON(
        @WebParam(name = "GetResultJSON", targetNamespace = "http://ws.clarin-pl.eu/wsg/tagger/", partName = "parameters")
        GetResultJSONRequestType parameters);

}
