
package pl.edu.pwr.services.morpho;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MorphoServicePortType", targetNamespace = "http://156.17.134.60/ws/morpho/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MorphoServicePortType {


    /**
     * Send request to server
     * 
     * @param parameters
     * @return
     *     returns pl.edu.pwr.services.morpho.SendRequestResponseType
     */
    @WebMethod(operationName = "SendRequest", action = "http://156.17.134.60/ws/morpho/#SendRequest")
    @WebResult(name = "SendRequestResponse", targetNamespace = "http://156.17.134.60/ws/morpho/", partName = "parameters")
    public SendRequestResponseType sendRequest(
        @WebParam(name = "SendRequest", targetNamespace = "http://156.17.134.60/ws/morpho/", partName = "parameters")
        SendRequestRequestType parameters);

    /**
     * Ask server for status of request with specific token
     * 
     * @param parameters
     * @return
     *     returns pl.edu.pwr.services.morpho.CheckStatusResponseType
     */
    @WebMethod(operationName = "CheckStatus", action = "http://156.17.134.60/ws/morpho/#CheckStatus")
    @WebResult(name = "CheckStatusResponse", targetNamespace = "http://156.17.134.60/ws/morpho/", partName = "parameters")
    public CheckStatusResponseType checkStatus(
        @WebParam(name = "CheckStatus", targetNamespace = "http://156.17.134.60/ws/morpho/", partName = "parameters")
        CheckStatusRequestType parameters);

    /**
     * Get result from server
     * 
     * @param parameters
     * @return
     *     returns pl.edu.pwr.services.morpho.GetResultResponseType
     */
    @WebMethod(operationName = "GetResult", action = "http://156.17.134.60/ws/morpho/#GetResult")
    @WebResult(name = "GetResultResponse", targetNamespace = "http://156.17.134.60/ws/morpho/", partName = "parameters")
    public GetResultResponseType getResult(
        @WebParam(name = "GetResult", targetNamespace = "http://156.17.134.60/ws/morpho/", partName = "parameters")
        GetResultRequestType parameters);

    /**
     * Get result from server in JSON
     * 
     * @param parameters
     * @return
     *     returns pl.edu.pwr.services.morpho.GetResultJSONResponseType
     */
    @WebMethod(operationName = "GetResultJSON", action = "http://156.17.134.60/ws/morpho/#GetResultJSON")
    @WebResult(name = "GetResultJSONResponse", targetNamespace = "http://156.17.134.60/ws/morpho/", partName = "parameters")
    public GetResultJSONResponseType getResultJSON(
        @WebParam(name = "GetResultJSON", targetNamespace = "http://156.17.134.60/ws/morpho/", partName = "parameters")
        GetResultJSONRequestType parameters);

}
