
package pl.edu.pwr.services.morpho;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MorphoService", targetNamespace = "http://156.17.134.60/ws/morpho/", wsdlLocation = "http://156.17.134.60/webservice/morpho/index.php?wsdl")
public class MorphoService
    extends Service
{

    private final static URL MORPHOSERVICE_WSDL_LOCATION;
    private final static WebServiceException MORPHOSERVICE_EXCEPTION;
    private final static QName MORPHOSERVICE_QNAME = new QName("http://156.17.134.60/ws/morpho/", "MorphoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://156.17.134.60/webservice/morpho/index.php?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MORPHOSERVICE_WSDL_LOCATION = url;
        MORPHOSERVICE_EXCEPTION = e;
    }

    public MorphoService() {
        super(__getWsdlLocation(), MORPHOSERVICE_QNAME);
    }

    public MorphoService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MORPHOSERVICE_QNAME, features);
    }

    public MorphoService(URL wsdlLocation) {
        super(wsdlLocation, MORPHOSERVICE_QNAME);
    }

    public MorphoService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MORPHOSERVICE_QNAME, features);
    }

    public MorphoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MorphoService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MorphoServicePortType
     */
    @WebEndpoint(name = "MorphoServicePort")
    public MorphoServicePortType getMorphoServicePort() {
        return super.getPort(new QName("http://156.17.134.60/ws/morpho/", "MorphoServicePort"), MorphoServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MorphoServicePortType
     */
    @WebEndpoint(name = "MorphoServicePort")
    public MorphoServicePortType getMorphoServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://156.17.134.60/ws/morpho/", "MorphoServicePort"), MorphoServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MORPHOSERVICE_EXCEPTION!= null) {
            throw MORPHOSERVICE_EXCEPTION;
        }
        return MORPHOSERVICE_WSDL_LOCATION;
    }

}
