
package pl.edu.pwr.services.serel;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SerelService", targetNamespace = "http://156.17.134.58/ws/serel/", wsdlLocation = "http://156.17.134.58/webservice/serel/index.php?wsdl")
public class SerelService
    extends Service
{

    private final static URL SERELSERVICE_WSDL_LOCATION;
    private final static WebServiceException SERELSERVICE_EXCEPTION;
    private final static QName SERELSERVICE_QNAME = new QName("http://156.17.134.58/ws/serel/", "SerelService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://156.17.134.58/webservice/serel/index.php?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERELSERVICE_WSDL_LOCATION = url;
        SERELSERVICE_EXCEPTION = e;
    }

    public SerelService() {
        super(__getWsdlLocation(), SERELSERVICE_QNAME);
    }

    public SerelService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERELSERVICE_QNAME, features);
    }

    public SerelService(URL wsdlLocation) {
        super(wsdlLocation, SERELSERVICE_QNAME);
    }

    public SerelService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERELSERVICE_QNAME, features);
    }

    public SerelService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SerelService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SerelServicePortType
     */
    @WebEndpoint(name = "SerelServicePort")
    public SerelServicePortType getSerelServicePort() {
        return super.getPort(new QName("http://156.17.134.58/ws/serel/", "SerelServicePort"), SerelServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SerelServicePortType
     */
    @WebEndpoint(name = "SerelServicePort")
    public SerelServicePortType getSerelServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://156.17.134.58/ws/serel/", "SerelServicePort"), SerelServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERELSERVICE_EXCEPTION!= null) {
            throw SERELSERVICE_EXCEPTION;
        }
        return SERELSERVICE_WSDL_LOCATION;
    }

}
