
package pl.edu.pwr.services.ner;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "nerws", targetNamespace = "http://156.17.135.31/nerws/ws/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Nerws {


    /**
     * 
     * @param text
     * @param model
     * @param outputFormat
     * @param inputFormat
     * @return
     *     returns pl.edu.pwr.services.ner.LinerResponse
     * @throws OperationFaultMsg
     */
    @WebMethod(operationName = "Annotate", action = "http://156.17.135.31/nerws/Annotate")
    @WebResult(name = "response", partName = "response")
    public LinerResponse annotate(
        @WebParam(name = "input_format", partName = "input_format")
        Format inputFormat,
        @WebParam(name = "output_format", partName = "output_format")
        Format outputFormat,
        @WebParam(name = "model", partName = "model")
        String model,
        @WebParam(name = "text", partName = "text")
        String text)
        throws OperationFaultMsg
    ;

    /**
     * 
     * @param token
     * @return
     *     returns pl.edu.pwr.services.ner.LinerResponse
     * @throws OperationFaultMsg
     */
    @WebMethod(operationName = "GetResult", action = "http://156.17.135.31/nerws/GetResult")
    @WebResult(name = "response", partName = "response")
    public LinerResponse getResult(
        @WebParam(name = "token", partName = "token")
        String token)
        throws OperationFaultMsg
    ;

}
